#!/bin/sh
# Generate runtime environment config for React app

cat > /app/build/env-config.js << EOF
window._env_ = {
  REACT_APP_FIREBASE_API_KEY: '${REACT_APP_FIREBASE_API_KEY}',
  REACT_APP_FIREBASE_AUTH_DOMAIN: '${REACT_APP_FIREBASE_AUTH_DOMAIN}',
  REACT_APP_FIREBASE_PROJECT_ID: '${REACT_APP_FIREBASE_PROJECT_ID}',
  REACT_APP_FIREBASE_STORAGE_BUCKET: '${REACT_APP_FIREBASE_STORAGE_BUCKET}',
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: '${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}',
  REACT_APP_FIREBASE_APP_ID: '${REACT_APP_FIREBASE_APP_ID}'
};
EOF

echo "Generated env-config.js with runtime environment variables"
