[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildArgs = [
  "REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY",
  "REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN",
  "REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID",
  "REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET",
  "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
  "REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID"
]

[deploy]
startCommand = "node simple-svg-server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
